#:kivy 1.0
<StartLayout>:
    t_name: t_name
    t_category: t_category
    t_count: t_count
    BoxLayout:
        orientation: 'vertical'
        height: '100dp'
        size_hint_y: None
        Label:
            text: "Task Name: "
            id: name_box
        Label:
            text: "Task Category: "
            id: cat_box
        Button:
            text: "Start"
            on_press: root.open_popup()
        TextInput:
